{% set version = "2.2.0" %}

package:
  name: gdal
  version: {{ version }}

source:
  fn: gdal-{{ version }}.tar.gz
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.gz
  sha256: d06546a6e34b77566512a2559e9117402320dd9487de9aa95cb8a377815dc360
  # Workaround to allow CircleCI to complete.
  patches:
    - clang.patch  # [osx]
    - prepend-dll.patch  # [win]
    # Fixes compilation problems with JPEG.
    # https://lists.osgeo.org/pipermail/gdal-dev/2016-January/043443.html
    - disable_jpeg12.patch  # [win]
    - windowshdf5.patch  # [win]
    - multiprocessor.patch  # [win]
    - install_scripts.patch

build:
  number: 2
  skip: True  # [py36 and linux]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - setuptools
    - cmake  # [win]
    - numpy x.x
    - hdf4
    - geos 3.5.1
    - hdf5 1.8.18|1.8.18.*
    - proj4 4.9.3
    - xerces-c
    - libnetcdf 4.4.*
    - libdap4 3.18.*  # [not win]
    - kealib
    - libtiff 4.0.*
    - libpng >=1.6.28,<1.7
    - zlib 1.2.*  # [not win]
    - jpeg 9*
    - postgresql
    - giflib 5.1.*  # [not win]
    - json-c  # [not win]
    - freexl
    - openjpeg
    - curl
    - expat
    - sqlite 3.13.*
    - libspatialite
    - vc   9  # [win and py27]
    - vc  10  # [win and py34]
    - vc  14  # [win and py>=35]

  run:
    - python
    - numpy x.x
    - hdf4
    - geos 3.5.1
    - hdf5 1.8.18|1.8.18.*
    - proj4 4.9.3
    - xerces-c
    - libnetcdf 4.4.*
    - libdap4 3.18.*  # [not win]
    - kealib
    - libtiff 4.0.*
    - libpng >=1.6.28,<1.7
    - zlib 1.2.*  # [not win]
    - jpeg 9*
    - libpq
    - giflib 5.1.*  # [not win]
    - json-c  # [not win]
    - freexl
    - openjpeg
    - curl
    - expat
    - sqlite 3.13.*
    - libspatialite
    - vc   9  # [win and py27]
    - vc  10  # [win and py34]
    - vc  14  # [win and py>=35]

test:
  files:
    - extra_tests.py
    - test_data/sites.dbf
    - test_data/sites.sbn
    - test_data/sites.sbx
    - test_data/sites.shp
    - test_data/sites.shx
  imports:
    - osr
    - gdal
    - gdalconst
    - osgeo
    - osgeo.ogr
    - osgeo.gdal
    - osgeo._gdal
    - osgeo._gdalconst
    - osgeo._ogr
    - osgeo._osr
  commands:
    - gdal_grid --version
    - gdal_rasterize --version
    - gdal_translate --version
    - gdaladdo --version
    - gdalenhance --version
    - gdalwarp --version
    - gdalinfo --formats
    - gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz  # [not win]
    - conda inspect linkages -p $PREFIX gdal  # [not win]
    - conda inspect objects -p $PREFIX gdal  # [osx]

about:
  home: http://www.gdal.org/
  license: MIT
  license_file: LICENSE.TXT
  summary: 'The Geospatial Data Abstraction Library (GDAL).'

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
    - gillins